In [6]:
import numpy as np
import matplotlib as plt
import csv
import pandas as pd

In [44]:
lst = []
with open("Kevin.csv",newline = '') as csvfile:
    eeg_kevin = csv.reader(csvfile, delimiter='\t',quotechar = '|')
    for i in eeg_kevin:
        lst.append(i)
kevin_df = pd.DataFrame(lst)

In [45]:
kevin_df

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.202000,...,80.000000,232.000000,176.000000,21.000000,208.000000,0.000000,0.000000,0.000000,1677538075.244776,0.000000
1,1.000000,3884.867297,2192.616724,992.909192,2607.129825,-5715.609278,-4919.551899,-1046.866303,-760.339291,0.202000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538075.723458,0.000000
2,2.000000,3887.504803,2191.275619,992.484509,2603.285325,-5709.216679,-4915.461530,-1047.045117,-764.474364,0.202000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538075.723486,0.000000
3,3.000000,3890.231715,2189.442776,991.255163,2603.039456,-5700.745368,-4923.016420,-1045.435792,-769.324692,0.202000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538075.723498,0.000000
4,4.000000,3891.595172,2190.895640,991.657495,2605.162871,-5707.093264,-4947.469228,-1043.759411,-765.793117,0.202000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538075.723512,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12072,40.000000,4461.698766,2256.654472,1408.003438,2627.358154,-5749.293357,-4922.256460,-805.646277,-532.284442,0.220000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538123.506687,0.000000
12073,41.000000,4455.954368,2258.621425,1407.489348,2629.638032,-5746.097058,-4926.257423,-805.981553,-531.815056,0.220000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538123.506693,0.000000
12074,42.000000,4457.049603,2260.990710,1407.869328,2626.575843,-5746.722906,-4928.939632,-807.702638,-533.111457,0.220000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538123.506700,0.000000
12075,43.000000,4460.514124,2261.907132,1408.517529,2624.653593,-5749.606281,-4929.543129,-806.361533,-531.882111,0.214000,...,176.000000,233.000000,16.000000,21.000000,176.000000,0.000000,0.000000,0.000000,1677538123.506706,0.000000
12076,44.000000,4467.756089,2260.521324,1407.735218,2627.514616,-5749.829799,-4927.576176,-805.132187,-530.831579,0.214000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1677538123.506713,0.000000